#!/usr/bin/env sh
set -e

if git diff --name-only HEAD@{1} HEAD | grep --silent '^yarn.lock'; then
  echo "📦 yarn.lock was changed."
  echo "Running yarn deps:reinstall to reinstall your dependencies..."
  yarn deps:reinstall
fi
